services:
  api:
    image: ghcr.io/dendianugerah/velld/api:latest
    env_file:
      - .env
    volumes:
      - api_data:/app/data
      - backup_data:/app/backups
    restart: unless-stopped

  web:
    image: ghcr.io/dendianugerah/velld/web:latest
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      ALLOW_REGISTER: ${ALLOW_REGISTER}
    depends_on:
      - api
    restart: unless-stopped

volumes:
  api_data:
  backup_data:
